const 지역 = [
    { label: '강남구', value: 'GANGNAM' },
    { label: '강동구', value: 'GANGDONG' },
    { label: '강북구', value: 'GANGBUK' },
    { label: '강서구', value: 'GANGSEO' },
    { label: '관악구', value: 'GWANAK' },
    { label: '광진구', value: 'GWANGJIN' },
    { label: '구로구', value: 'GURO' },
    { label: '금천구', value: 'GEUMCHEON' },
    { label: '노원구', value: 'NOWON' },
    { label: '도봉구', value: 'DOBONG' },
    { label: '동대문구', value: 'DONGDAEMUN' },
    { label: '동작구', value: 'DONGJAK' },
    { label: '마포구', value: 'MAPO' },
    { label: '서대문구', value: 'SEODAEMUN' },
    { label: '서초구', value: 'SEOCHO' },
    { label: '성동구', value: 'SEONGDONG' },
    { label: '성북구', value: 'SEONGBUK' },
    { label: '송파구', value: 'SONGPA' },
    { label: '양천구', value: 'YANGCHEON' },
    { label: '영등포구', value: 'YEONGDEUNGPO' },
    { label: '용산구', value: 'YONGSAN' },
    { label: '은평구', value: 'EUNPYEONG' },
    { label: '종로구', value: 'JONGNO' },
    { label: '중구', value: 'JUNG' },
    { label: '중랑구', value: 'JUNGRANG' },
  ];
  
  export default 지역;
  