// 지역 텍스트
const 지역 = [
    { label: '강남구'},
    { label: '강동구'},
    { label: '강북구'},
    { label: '강서구'},
    { label: '관악구'},
    { label: '광진구'},
    { label: '구로구'},
    { label: '금천구'},
    { label: '노원구'},
    { label: '도봉구'},
    { label: '동대문구'},
    { label: '동작구'},
    { label: '마포구'},
    { label: '서대문구'},
    { label: '서초구'},
    { label: '성동구'},
    { label: '성북구'},
    { label: '송파구'},
    { label: '양천구'},
    { label: '영등포구'},
    { label: '용산구'},
    { label: '은평구'},
    { label: '종로구'},
    { label: '중구'},
    { label: '중량구'},
];
  
export default 지역; 